# Generated by Django 2.1.5 on 2019-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190218_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='full_image',
            field=models.ImageField(upload_to='gallery/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lazy_image',
            field=models.ImageField(upload_to='gallery/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_image',
            field=models.ImageField(upload_to='gallery/<django.db.models.fields.CharField>/'),
        ),
    ]
