# Generated by Django 2.1.5 on 2019-02-18 07:17

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190218_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='full_image',
            field=models.ImageField(upload_to=website.models.upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lazy_image',
            field=models.ImageField(upload_to=website.models.upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_image',
            field=models.ImageField(upload_to=website.models.upload_path),
        ),
    ]
