# Generated by Django 2.1.5 on 2019-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190218_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='display_size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('high', 'High'), ('tall', 'Tall'), ('full', 'Full')], default='small', max_length=6),
        ),
    ]
